# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/download_strategy.rb"
class Cvcloud < Formula
  desc "client tool to use cvcloud"
  homepage "https://gitlab.com/kindaicvlab/cvcloud/cvcloud"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tenzen-y/cvcloud/releases/download/v1.0.0/cvcloud_1.0.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "1ab2158ced8a09973e77f012eb9999ad1baee0e03d7b32e97fbfc373293e8aef"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/tenzen-y/cvcloud/releases/download/v1.0.0/cvcloud_1.0.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "90fcd3c290d035e8860a447eb2e1e5715e966b2e3e5a23cce927a384683d6f6f"
  end

  def install
    bin.install "cvcloud"
  end

  test do
    system "#{bin}/cvcloud version"
  end
end
