# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/download_strategy.rb"
class Cvcloud < Formula
  desc "client tool to use cvcloud"
  homepage "https://gitlab.com/kindaicvlab/cvcloud/cvcloud"
  version "1.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tenzen-y/cvcloud/releases/download/v1.1.4/cvcloud_1.1.4_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "1f448635b3e1f2d57cc0090b23d689862393bba35d58d93d7bd3f50da9ff33ee"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/tenzen-y/cvcloud/releases/download/v1.1.4/cvcloud_1.1.4_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "1c19626f47548944457c1c086cf8adc8b2419756bbbdca3efc390e072c7ac5b9"
  end

  def install
    bin.install "cvcloud"
  end

  test do
    system "#{bin}/cvcloud version"
  end
end
